# docker run --name api-nodejs-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=api-solid -p 5432:5432 bitnami/postgresql:latest
services:
    api-solid-pg:
        image: bitnami/postgresql
        container_name: api-nodejs-solid-pg
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
            - POSTGRESQL_DATABASE=api-solid
        ports:
            - "5432:5432"
